package vista;

import java.awt.*;
import javax.swing.*;

/**
 * Con esta clase que hereda de JFrame mostramos por pantalla 
 * la ventana principal de la aplicación
 *
 * @author Daniel Paz Lorenzo
 */
public class VentanaInicio extends javax.swing.JFrame {

    //Recogemos la resolución de la pantalla del dispositivo donde se ejecuta
    Toolkit miPantalla = Toolkit.getDefaultToolkit();
    Dimension tamanoMiPantalla = miPantalla.getScreenSize();
    //Declaración de objeto que contiene la imagen de icono
    Image icono = miPantalla.getImage("src/vista/imagenes/icono.jpg");

    /**
     * Constructor de la clase
     */
    public VentanaInicio() {
        initComponents();
        setVisible(true);
    }

    /**
     * Método main de la aplicación que genera pantalla de inicio mediante
     * instancia objeto de la misma clase
     *
     * @param args
     */
    public static void main(String[] args) {
        VentanaInicio panInicio = new VentanaInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonReserva = new javax.swing.JButton();
        botonSalirApp = new javax.swing.JButton();
        etiqImagenLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación empresa BK");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(this.icono);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        botonReserva.setText("Reservar Salón Habana");
        botonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservaActionPerformed(evt);
            }
        });

        botonSalirApp.setText("Salir de la aplicación");
        botonSalirApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirAppActionPerformed(evt);
            }
        });

        etiqImagenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/logotipo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalirApp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(etiqImagenLogo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(etiqImagenLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonReserva)
                    .addComponent(botonSalirApp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que recive como parámetro el evento del botón de reserva e
     * instancia un objeto de la clase ventana reserva
     *
     * @param evt
     */
    private void botonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservaActionPerformed
        VentanaReservas venReservas = new VentanaReservas();
    }//GEN-LAST:event_botonReservaActionPerformed

    /**
     * Método que recive el evento del botón de salir y cierra la aplicación con
     * llamada a método de sistema
     *
     * @param evt
     */
    private void botonSalirAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirAppActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirAppActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonReserva;
    private javax.swing.JButton botonSalirApp;
    private javax.swing.JLabel etiqImagenLogo;
    // End of variables declaration//GEN-END:variables
}
